[language-server.ltex-ls]
command = "ltex-ls"


[[language]]
name = "latex"
language-servers = [ "ltex-ls" ]
file-types = ["tex"]
scope = "source.tex"
roots = []

[[language]]
name = "rust"
auto-format = false

# [language-server.pylsp.config]
# pylsp.plugins.pycodestyle.enabled = true

[[language]]
name = "python"
language-servers = [ "pyright", "ruff" ]
auto-format = false

[[language]]
name = "haskell"
indent = { tab-width = 2, unit = " " }


[language-server.matlab-ls]
command = "node"
args = [ "C:/Users/afaber/Projects/MATLAB-language-server/out/index.js", "--stdio" ]

[language-server.matlab-ls.config.MATLAB]
indexWorkspace = false
installPath = "C:/Program Files/MATLAB/R2024b"
matlabConnectionTiming = "onStart"
telemetry = false

[language-server.rust-analyzer.config]
# check.command = "clippy"
files.excludeDirs = [ ".direnv", ".git", "target" ]
