[[language]]
name = "latex"
language-server = { command = "ltex-ls" }
file-types = ["tex"]
scope = "source.tex"
roots = []

[[language]]
name = "rust"
config = { "cargo.features" = ["wgpu"] }
auto-format = false

[[language]]
name = "python"
auto-format = false
config = { pylsp.plugins.pycodestyle.enabled = false }
